### ISSUE TITLE
Current Solution Debug

### ISSUE THREAD

**Issue by carolemlago** [hackbrightacademy/tech-interview-prep#4]
In the current solution code, the function goes over the first number of the list and return the result based only on that first number. This code needs to be in a while loop to make sure it keeps iterating over each number on the list and return based on the total count of even or odds.

def get_even_or_odds(numbers):
    count_even = 0
    count_odd = 0
    
    while True:
        for num in numbers:
            if num % 2 == 0:
                count_even = count_even + 1
            
            elif num % 2 != 0:
                count_odd = count_odd + 1
            
        if count_even > count_odd:
            return "Even"
            
        elif count_odd > count_even:
            return "Odd"
            
        else:
            return "Even and odd"
            
            
num_list = [1, 2, 3, 4, 5, 6, 7, 8, 10]

print(get_even_or_odds(num_list))

**Comment by poemusica** [comment]
Thank you for your comment. 
The current code is correct as-is. Adding a `while` loop is not necessary. 

The `for` loop will iterate through all the numbers in the list and independently evaluate whether a given number is even or odd and increment the corresponding counter. 

Then, outside of the `for` loop, we do a series of checks to determine which string we should return as the final result.

Wrapping our entire solution in a `while True` loop won't cause an error, because the code will execute one of the three `return` statements, thus breaking out of the `while` loop. However, it is not needed. I recommend running our solution as-is in order to demonstrate this.

**Comment by carolemlago** [comment]
> Thank you for your comment. The current code is correct as-is. Adding a `while` loop is not necessary.
> 
> The `for` loop will iterate through all the numbers in the list and independently evaluate whether a given number is even or odd and increment the corresponding counter.
> 
> Then, outside of the `for` loop, we do a series of checks to determine which string we should return as the final result.
> 
> Wrapping our entire solution in a `while True` loop won't cause an error, because the code will execute one of the three `return` statements, thus breaking out of the `while` loop. However, it is not needed. I recommend running our solution as-is in order to demonstrate this.

Thank you. I must have had some kind of indentation error because it wasn't iterating over the whole list.
